---
version: 2
updates:
  - package-ecosystem: docker
    directory: "/.devops/docker"
    schedule:
      interval: weekly
      time: "06:00"
    open-pull-requests-limit: 0
    reviewers:
      - LogPass/devops-devs
    commit-message:
      prefix: "build(deps): "
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    open-pull-requests-limit: 0
    reviewers:
      - LogPass/devops-devs
    commit-message:
      prefix: "chore(deps): "
