---
name: depup-dockerfiles
'on':
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOCKERFILE_PATH: .devops/docker/Dockerfile
    strategy:
      matrix:
        context:
          - repo: microsoft/vcpkg
            tag-prefix: ''
          - repo: Kitware/CMake
            tag-prefix: v
    steps:
      - name: clean after previous run
        working-directory: /tmp
        run: |
          sudo rm -rf "${{ github.workspace }}" \
          && mkdir -p "${{ github.workspace }}"
      - uses: actions/checkout@v3
      - name: populate dynamic environments
        run: |
          SLUG="$(echo '${{ matrix.context.repo }}' | cut -d/ -f 2)"

          echo "SLUG=${SLUG}" >> ${GITHUB_ENV}
          echo "SLUG_UPPERCASE=${SLUG^^}" >> ${GITHUB_ENV}
      - name: "check ${{ matrix.context.repo }} version"
        id: depup
        uses: reviewdog/action-depup@v1.4.5
        with:
          file: "${{ env.DOCKERFILE_PATH }}"
          version_name: "${{ env.SLUG_UPPERCASE }}_VERSION"
          repo: "${{ matrix.context.repo }}"
      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: "${{ secrets.BOT__GITHUB_TOKEN }}"
          title: >-
            build(deps): bump ${{ env.SLUG }} from
            ${{ steps.depup.outputs.current }} to
            ${{ steps.depup.outputs.latest }} in ${{ env.DOCKERFILE_PATH }}
          commit-message: >-
            build(deps): bump ${{ env.SLUG }} from
            ${{ steps.depup.outputs.current }} to
            ${{ steps.depup.outputs.latest }}
          body: >-
            Update `${{ env.SLUG }}` from
            [${{ steps.depup.outputs.current }}](
            https://github.com/${{matrix.context.repo}}/releases/tag/${{matrix.context.tag-prefix}}${{steps.depup.outputs.current}})
            to [${{ steps.depup.outputs.latest }}](
            https://github.com/${{matrix.context.repo}}/releases/tag/${{matrix.context.tag-prefix}}${{steps.depup.outputs.latest}})


            This PR is auto generated by
            [depup workflow](
            https://github.com/${{github.repository}}/actions?query=workflow%3Adepup-dockerfile).
          branch: "dependencies/docker/Dockerfile/${{ env.SLUG }}"
          delete-branch: true
          base: main
          team-reviewers: devops-devs
