---
name: misspell
'on':
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
  build:
    uses: LogPass/reusable-workflows/.github/workflows/misspell.yml@main
    with:
      pr-reviewers: |
        bbarwik
        skarzi
    secrets:
      token: "${{ secrets.BOT__GITHUB_TOKEN }}"
